(function($){function headerregion(){var logo="<div class='logo col-xs-4 col-sm-2 col-md-2'></div>";var menu="<nav class='header-menu col-xs-12 col-sm-7 col-md-8'></nav>";var bookinblock="<div class='online-booking rtecenter col-xs-8 col-sm-3 col-md-2'>";$("header").append("<div class='container'><div class='row'>"+logo+menu+bookinblock+"</div></div>");$.getJSON('js/json/header.json',function(data){$.each(data,function(key,val){$.each(val.logo,function(key,val){$("header .logo").append("<a  href='/'  id='logo' href='/' title='"+val.logotitle+"' rel='home'><img   alt='Eco Nature Resorts Wayanad - Banasura' title='Eco Nature Resorts Wayanad - Banasura'  src='"+val.logosrc+"'></a>");});$.each(val.menu,function(key,val){if($("body").hasClass("home")){val.menulinks.shift();}
var headermenu=$("<ul class='menu'></ul>");var totallen=val.menulinks.length;$.each(val.menulinks,function(key,val){if(key==totallen-1){var links="<li class='leaf last'><a href='"+val.menuurl+"' title='"+val.title+"'>"+val.menutext+"</a></li>";}
else if(key==0){var links="<li class='leaf first'><a href='"+val.menuurl+"' title='"+val.title+"'>"+val.menutext+"</a></li>";}
else{var links="<li class='leaf'><a href='"+val.menuurl+"' title='"+val.title+"'>"+val.menutext+"</a></li>";}
headermenu.append(links);});$("header .header-menu").append(headermenu);});$.each(val.onlinebooking,function(key,val){var contact="<div class='contact-no mob-hide'>"+val.contactnumber+"</div>";var bookingbtn="<div class='book-btn btn btn-default btn-raised mob-hide'>"+val.bookinglabel+"</div>";$("header .online-booking").append(contact+bookingbtn+"<div class='toggle-menu'>menu</div>");});});$(document).on("click",".online-booking .book-btn",function(){$('.online-booking-menu').addClass("active");});$(document).on("click",".toggle-menu",function(){$(".header-menu").slideToggle("slow",function(){});});});}
function viewallreview()
{var jsonurl="/review-comments.json";$.getJSON(jsonurl,function(data){$.each(data,function(key,val){var imgblock="<img src='"+val.photograph+"'>";var contentblock="<p>"+val.reviewdescription+"</p>";var nameblock="<div class='profile-name'>"+val.profilename+"</div>";$(".viewAllReview").append("<li>"+imgblock+contentblock+nameblock+"</li>");});if($('#grid').length>0){new AnimOnScroll(document.getElementById('grid'),{minDuration:0.4,maxDuration:1,viewportFactor:0.2});}});}
$(document).ready(function(){if(!$('body').hasClass('home'))
{headerregion();}
viewallreview();});})(jQuery);
